#!/usr/bin/env bash
# this script prints 10 times "Best School"
i=0
while (( i < 10 ))
do
	echo "Best School"
	if (( i == 4 ))
	then
		echo "bad luck"
	elif (( i == 8 ))
	then
		echo "good luck"
	fi
	(( i = i + 1 ))
done
