#!/usr/bin/env bash
# this script prints 10 times "Best School"
i=0
j=0
while (( i <= 12 ))
do
	j=0
	while (( j < 60 ))
	do
		if (( j == 0 ))
		then
			echo "Hour: $i"
		else
			echo "$j"
		fi
		(( j = j + 1 ))
	done
	(( i = i + 1 ))
done
