#!/usr/bin/env bash
# set localhost to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts /etc/hosts.new
sed -i 's/.*localhost$/127.0.0.2\tlocalhost/' /etc/hosts.new

if grep -q "facebook.com" /etc/hosts.new
then
	sed -i 's/.*facebook.com$/8.8.8.8\tfacebook.com/' /etc/hosts.new
else
	echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts.new
fi

cp -f /etc/hosts.new /etc/hosts
rm -f /etc/hosts.new
